---
title: "SFAt compared to other existing R packages for SFA"
author: "Vaclav Hausenblas"
date: "2016-04-01"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r Init}
require(SFAt)
# require(msm) # package for drawing from truncated-normal distribution
require(data.table) # for more convenient data manipulation
```

### Example dataset

Lets generate some randomly simulated production data...

```{r}

dtDT <- as.data.table(sim_data_cs(500))

```

and explore the production data and simulated inefficiency term.

```{r, fig.width = 10, fig.height = 10}
# require(GGally)
# ggpairs(dtDT)

plot(dtDT)
```

```{r}
hist(dtDT$y)
hist(dtDT$u)
hist(dtDT$eps)

```

## OLS model

We might be interested in simple OLS model for LR test (and starting values of parameters).

```{r}

lmfit <- lm(y ~ x1 + x2 + z1 + z2, data = dtDT)
summary(lmfit)

```

## SFA model

```{r}
sfat <- SFAt::sfa.fit(y = dtDT$y,
                     X = as.matrix(dtDT[, .(x1, x2)]),
                     CM = as.matrix(dtDT[, .(z1, z2)]),
                     spec = "bc95",
                     deb = F,
                     opt_method = "BFGS"
                     # control_opt = list(maxit = 300, trace = T)
)
summary(sfat)
```


<!-- ### benchmark with sfa package -->

<!-- ```{r} -->
<!-- require(sfa) -->

<!-- summary(sfa::sfa(y ~ x1 + x2, -->
<!--                  data = as.data.frame(data1), -->
<!--                  fun = "tnormal", -->
<!--                  form = "production")) -->

<!-- ``` -->


### benchmark with frontier package methods

```{r}
require(frontier)

frontest <- frontier::sfa(y ~ x1 + x2 | z1 + z2,
                          data = dtDT,
                          ineffDecrease = T,
                          truncNorm = T,
                          muBound = 0,
                          maxit = 100)

print(summary(frontest))
print(lrtest(frontest))

```

## Example 2

```{r}
data("front41Data")

sfa2 <- SFAt::sfa.fit(y = log(front41Data$output), 
                         X = cbind(capital = log(front41Data$capital), 
                                   labour = log(front41Data$labour)), 
                         dist = "tnorm",
                         spec = NULL,
                         deb = F)

print(summary(sfa2))
```


```{r}
sfa2_front <- frontier::sfa( log( output ) ~ log( capital ) + log( labour ),
                             truncNorm = T,
                             data = front41Data )

print(summary(sfa2_front))
print(lrtest(sfa2_front))
```

