---
title: "Intro to SFAplus package"
author: "Vaclav Hausenblas"
date: "2016-04-01"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

SFAplus package aims ...

```{r}
source("simulate_data.R")

require(SFAplus)

require(msm) # package for simulating random datasets
require(data.table)
```


### Simulate random data
```{r}

dtDT <- as.data.table(sim_data(500))

```


```{r}
# require(GGally)
# ggpairs(dtDT)

plot(dtDT)
hist(dtDT$y)
hist(dtDT$u)

```

## Fit a SFA model

```{r}

est <- SFAplus::sfa.fit(y = dtDT$y,
                        X = as.matrix(dtDT[, .(1, x1, x2)]),
                        Z = as.matrix(dtDT[, .(1, z1, z2)]),
                        intercept = F,
                        intercept_Z = F,
                        spec  = "bc95",
                        deb = F,
                        opt_method = "BFGS",
                        # control_opt = list(maxit = 300),
                        trace = T)

print(est)
```


# fit an OLS model

for LR test and starting values of parameters

```{r}

lmfit <- lm(y ~ x1 + x2 + z1 + z2, data = dtDT)
summary(lmfit)

```





<!-- # BOUNDS ------------------------------------------------------------------ -->
<!-- # set lower bounds, important for sigmas -->
<!-- lowerb <- c(-Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, 0.0001, 0.0001) -->

<!-- # initpar = c(lmfit$coefficients[1:4], 0, lmfit$coefficients[5:6], 1, 1) -->
<!-- # OR -->
<!-- initpar = c(rep(0, 4+3), 1, 1) -->


<!-- # estimate by BFGS method with bounds -->
<!-- est <- optim(initpar, fn = ll, method = "BFGS", control = list(trace = F, REPORT = 1, maxit = 300), hessian = T, -->
<!--              nbeta = 4, ngamma = 3, -->
<!--              y = dtDT$y, -->
<!--              X = as.matrix(dtDT[, .(1, x1, x2, x1x2)]), -->
<!--              Z = as.matrix(dtDT[, .(1, z1, z2)])) -->
<!-- print(est) -->


## Compute summary statistics

```{r}

var_beta <- diag(solve(est$hessian))
tvalue <- est$par/sqrt(var_beta)
coef.table <- cbind(est$par, sqrt(var_beta), tvalue)
colnames(coef.table) <- c("Estimate", "Std. Error","t value")
row.names(coef.table) <- names(est$par)
ll_sfa <- -est$value
ll_ols <- logLik(lmfit)
LRtest <- 2*(ll_sfa - ll_ols)[1]
chisq_df <- (4+3+2) - attributes(logLik(lmfit))$df
p_value <- pchisq(LRtest, chisq_df, lower.tail = FALSE)

```


