// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ll_cs_exp_cpp
double ll_cs_exp_cpp(const NumericVector& pars, const IntegerVector& indeces, const NumericVector& y, const NumericMatrix& X, const SEXP& CV_u, const SEXP& CV_v, const SEXP& CM, const int ineff, const bool deb);
RcppExport SEXP _SFAt_ll_cs_exp_cpp(SEXP parsSEXP, SEXP indecesSEXP, SEXP ySEXP, SEXP XSEXP, SEXP CV_uSEXP, SEXP CV_vSEXP, SEXP CMSEXP, SEXP ineffSEXP, SEXP debSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type indeces(indecesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type CV_u(CV_uSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type CV_v(CV_vSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type CM(CMSEXP);
    Rcpp::traits::input_parameter< const int >::type ineff(ineffSEXP);
    Rcpp::traits::input_parameter< const bool >::type deb(debSEXP);
    rcpp_result_gen = Rcpp::wrap(ll_cs_exp_cpp(pars, indeces, y, X, CV_u, CV_v, CM, ineff, deb));
    return rcpp_result_gen;
END_RCPP
}
// rtnorm_
NumericVector rtnorm_(int n, double mean, double sd, double lower, double upper);
RcppExport SEXP _SFAt_rtnorm_(SEXP nSEXP, SEXP meanSEXP, SEXP sdSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(rtnorm_(n, mean, sd, lower, upper));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SFAt_ll_cs_exp_cpp", (DL_FUNC) &_SFAt_ll_cs_exp_cpp, 9},
    {"_SFAt_rtnorm_", (DL_FUNC) &_SFAt_rtnorm_, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_SFAt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
