# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ll_cs_exp <- function(params, y, X, ineff, deb) {
    .Call('SFAt_ll_cs_exp', PACKAGE = 'SFAt', params, y, X, ineff, deb)
}

