# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ll_cs_exp_cpp <- function(pars, indeces, y, X, CV_u, CV_v, CM, ineff, deb) {
    .Call('_SFAt_ll_cs_exp_cpp', PACKAGE = 'SFAt', pars, indeces, y, X, CV_u, CV_v, CM, ineff, deb)
}

